# ベクトルとは

$$
\mathbf{a} = (1, 2) \\
\mathbf{b} = \begin{pmatrix}
        1 \\
        2 \\
        3 \\
        4
        \end{pmatrix}
$$
などのように，数を並べたものと思っていて良い。

今回はこれに対する演算をnumpyというライブラリを使って学んでいこう！

## Tips
ベクトルって向きとか，大きさを表す量じゃないの？？

例） 
* 話のベクトルを合わせよう
* チームのベクトルを最大化できるようにしよう

など，普段耳にする「ベクトル」という言葉は**向き**と**大きさ**を持つものに聞こえる

この時に使うベクトルは高校数学で扱う「**幾何ベクトル**」としての意味である。

ベクトルは座標平面（ユークリッド空間）で考えると，幾何学的に向きと大きさを持つ量として捉えることができる。

これはただの解釈の違いで，

* ベクトルを単に数を並べたものとして解釈するか
* ベクトルを幾何学的に向きと大きさを持つ量として解釈するか

の違いである。

## numpyとは

数値計算用のライブラリ

行列の演算などを行う場合に用いられる．

In [5]:
#ライブラリのインポート
import numpy as np

## 列ベクトルと行ベクトル

列ベクトルは
$$
\mathbf{b} = \begin{pmatrix}
        1 \\
        2 \\
        3 \\
        4
        \end{pmatrix}
$$
のように数を縦に並べたもの

<br>
行ベクトルは
$$
\mathbf{a} = (1, 2) \\
$$
のように数を横に並べたもの

その要素数を次元という．
$$
\mathbf{b} = \begin{pmatrix}
        1 \\
        2 \\
        3 \\
        4
        \end{pmatrix}
$$
だと，次元は4である．

np.ndarray.shapeで確認ができる

In [6]:
# ベクトルを定義してみよう
a = np.array([[1, 2]])
b = np.array([[1],
              [2],
              [3],
              [4]])

print("行ベクトル", a, a.shape)
print("列ベクトル\n", b, b.shape)

行ベクトル [[1 2]] (1, 2)
列ベクトル
 [[1]
 [2]
 [3]
 [4]] (4, 1)


In [ ]:
# c = [[3 4]]
# d = [[3]
#      [4]
#      [5]
#      [6]
#となるようにベクトルを定義してみよう

c = #WRITE ME
d = #WRITE ME

print(c)
print(d)

#それぞれのベクトルのshapeを出力

c_shape = #WRITE ME
d_shape = #WRITE ME

print(c_shape)
print(d_shape)

## 値の取り出し
行ベクトルであれば，
`a[0][j-1]`または`a[0,j-1]`でj番目の要素を取り出せる

列ベクトルであれば，
`a[i-1][0]`または`a[i-1,0]`でj番目の要素を取り出せる

基本的には，二次元リストと同じ取り出し方．

In [ ]:
#行ベクトル
print("a:", a)
#a[0]には[1 2]が入っている
print("aの0番目の要素:", a[0, 0])
print("aの1番目の要素:", a[0, 1])
#列ベクトル
print("b:\n",b)
#b[0]には[1]が入っている
print("bの0番目の要素:", b[0, 0])
print("bの1番目の要素:", b[1, 0])
print("bの2番目の要素:", b[2, 0])
print("bの3番目の要素:", b[3, 0])

a: [[1 2]]
aの0番目の要素: 1
aの1番目の要素: 2
b:
 [[1]
 [2]
 [3]
 [4]]
bの0番目の要素: 1
bの1番目の要素: 2
bの2番目の要素: 3
bの3番目の要素: 4


In [ ]:
#行ベクトルcの１番目の要素を抜き出そう

c_1 = #WRITE ME

#列ベクトルdの３番目の要素を抜き出そう

d_3 = #WRITE ME

print(c_1)
print(d_3)

## ベクトルの足し算と引き算

ベクトルには足し算と引き算がある

計算方法は要素ごとに足したり，引いたりする．

例）以下の例は引き算についても同様
$$
\mathbf{a} = (1, 2) \\
\mathbf{c} = (3, 4) \\
\mathbf{a} + \mathbf{c} = (1 + 3, 2 + 4)=(4, 6) \\
\mathbf{b} = \begin{pmatrix}
        1 \\
        2 \\
        3 \\
        4
        \end{pmatrix} ，
\mathbf{d} = \begin{pmatrix}
        3 \\
        4 \\
        5 \\
        6
        \end{pmatrix} \\
\mathbf{b} + \mathbf{d} = 
        \begin{pmatrix}
        1 + 3 \\
        2 + 4 \\
        3 + 5\\
        4 + 6
        \end{pmatrix} 
        = 
        \begin{pmatrix}
        4 \\
        6 \\
        8 \\
        10
        \end{pmatrix} \\
$$

numpy ではそれぞれ`+`，`-`演算子で計算可能．

### 注意
足し算と引き算については，次元と形（shape）が一致している必要がある．

例えば，下記の例は次元は一致しているが，形が違うので計算できない．
$$
\mathbf{a} = (1, 2) \\
\mathbf{e} = \begin{pmatrix}
        1 \\
        2 
        \end{pmatrix}\\
\mathbf{a} + \mathbf{e} = ✖️（計算できない）
$$

In [ ]:
c = np.array([[3, 4]])
d = np.array([[3],
             [4],
             [5],
             [6]])
print("足し算", a+c)
print("引き算\n", d-b)

足し算 [[4 6]]
引き算
 [[2]
 [2]
 [2]
 [2]]


In [ ]:
# e = [[5 6]]
# f = [[5]
#      [6]
#      [7]
#      [8]
#として，a+e, b+fを計算してみよう
e = #WRITE ME
f = #WRITE ME
sum_result = #WRITE ME
sub_result = #WRITE ME

print(sum_result)
print(sub_result)

## ベクトルのスカラー（実数）倍

ベクトルにはスカラー倍がある．

計算方法は，要素ごとに掛け算すれば良い．

例）
$$
\mathbf{a} = (1, 2)\\
3 \times  \mathbf{a} = (3 \times 1, 3 \times 2)=(3, 6) \\
\mathbf{b} = \begin{pmatrix}
        1 \\
        2 \\
        3 \\
        4
        \end{pmatrix} \\
\frac{1}{2} \times \mathbf{b} = 
        \begin{pmatrix}
        \frac{1}{2} \times 1 \\
        \frac{1}{2} \times 2 \\
        \frac{1}{2} \times 3 \\
        \frac{1}{2} \times 4
        \end{pmatrix} 
        = 
        \begin{pmatrix}
        0.5 \\
        1.0 \\
        1.5 \\
        2.0
        \end{pmatrix} \\
$$
numpyでは`*`演算子で計算できる．

In [7]:
#スカラー倍の計算
print(3*a)
print(1/2 * b)

[[3 6]]
[[0.5]
 [1. ]
 [1.5]
 [2. ]]


In [ ]:
# c * 4, d * 0.66を計算してみよう

c_res = #WRITE ME, c×4
d_res = #WRITE ME, d×0.66

print(c_res)
print(d_res)

## ベクトルの内積

ベクトル同士の掛け算の一種

計算方法は要素ごとに掛け算して，足し合わせる

例）
$$
\mathbf{a} = (1,2) \\
\mathbf{g} = \begin{pmatrix}
        3 \\
        4
        \end{pmatrix} \\
<\mathbf{a}, \mathbf{g}> = \mathbf{a} •\mathbf{g}=1 \times 3 + 2 \times 4 = 11
$$

### 注意
これまた，次元と形に関して縛りがある．（より詳しくは行列の内積の時に説明する）

それは，
左から掛け算されるベクトルの列数と右から掛け算されるベクトルの行数が一致している必要があるということである．

例）
$$
\mathbf{a} = (1,2,3) \\
\mathbf{g} = \begin{pmatrix}
        3 \\ 
        4
        \end{pmatrix} \\
<\mathbf{a}, \mathbf{g}> = \mathbf{a} •\mathbf{g}=1 \times 3 + 2 \times 4 + 3 \times ?? = ✖️（計算できない）
$$
つまり，numpyのshape属性で見た時に，
```python
a.shape = (1, m) #行ベクトル
g.shape = (n, 1) #列ベクトル
```
であり，m=nの時に<a, b>が計算できるということである．

内積の計算には，`np.dot()`を用いるか，`np.matmul()`または，`@`演算子で計算できる．

In [17]:
a = np.array([[1, 2]])
g = np.array([[3], 
              [4]])
print("dot():", np.dot(a, g))
print("matmul():", np.matmul(a, g))
print("@ operator:", a @ g)

dot(): [[11]]
matmul(): [[11]]
@ operator: [[11]]
1.9999999999999


In [ ]:
#次のベクトルの内積を計算せよ．
b = np.array([[1],
              [2],
              [3],
              [4]])
h = np.array([[1, 2, 3, 4]])

inner_product = #WRITE ME
print(inner_product)

# 行列とは
数を縦または横に並べたもの

行ベクトルを縦に，列ベクトルを横に並べたもの，と解釈しても良い．

縦方向の数を行数，横方向の数を列数という．（下の行列の行数と列数を考えてみよう）

例）
$$
A = \begin{pmatrix}
        1 & 2 \\
        2 & 3 \\
        3 & 4 \\
        4 & 5
        \end{pmatrix} \\
B = \begin{pmatrix}
        1 & 3 & 5\\
        2 & 4 & 6
        \end{pmatrix}
$$
計算規則は，ベクトルの時と基本的には同じ．

shapeは`(行数，列数)`という形で表される．

In [18]:
#行列の定義
A = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5]])

C = np.array([[2, 4],
              [5, 7],
              [8, 10],
              [11, 13]])
print("Aの形:",A.shape)
print("Cの形:",C.shape)

Aの形: (4, 2)
Cの形: (4, 2)


In [ ]:
# B = [[1 3 5]
#      [2 4 6]]
# D = [[4 9 16]
#      [1 8 27]]
#として行列を定義しよう

B = #WRITE ME
D = #WRITE ME

print(B)
print(D)

## 値の取り出し

行列の値の取り出しは，`A[i-1, j-1]`で`i行j列目`の値を取り出すことができる．

In [ ]:
#Aの2行1列目を取り出す
print("行列A")
print(A)
print("2行1列目", A[1, 0])
print("4行2列目", A[3, 1])

行列A
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
2行1列目 2
4行2列目 5


In [ ]:
#Bの2行3列目を取り出そう
B_23 = #WRITE ME

#Dの2行1列目を取り出そう
D_21 = #WRITE ME

print(B_23)
print(D_21)

## 行列の足し算と引き算，スカラー倍
要素ごとに足す（引く，スカラー倍）．

$$
A = \begin{pmatrix}
        1 & 2 \\
        2 & 3 \\
        3 & 4 \\
        4 & 5
        \end{pmatrix} \\
C = \begin{pmatrix}
        2 & 4 \\
        5 & 7 \\
        8 & 10 \\
        11 & 13 
    \end{pmatrix}
$$
$$
A + C = \begin{pmatrix}
        1+2 & 2+4 \\
        2+5 & 3+7 \\
        3+8 & 4+10 \\
        4+11 & 5+13 
    \end{pmatrix}
    = 
     \begin{pmatrix}
        3 & 6 \\
        7 & 10 \\
        11 & 14 \\
        15 & 18 
    \end{pmatrix}
$$

$$
2 \times A = \begin{pmatrix}
        2 \times 1 & 2 \times 2 \\
        2 \times 2 & 2 \times 3 \\
        2 \times 3 & 2 \times 4 \\
        2 \times 4 & 2 \times 5
        \end{pmatrix} 
        =
        \begin{pmatrix}
        2 & 4 \\
        4 & 6 \\
        6 & 8 \\
        8 & 10
        \end{pmatrix}
$$

numpy ではそれぞれ`+`，`-`，`*`演算子で計算可能．

### 注意
足し算と引き算は形が完全に一致している場合のみに計算可能（numpyの仕様上の例外あり）



In [19]:
#A,Cを足し算
print("A+Cの結果")
print(A + C)
print()
#Aに2を掛け算
print("2*Aの結果")
print(2*A)

A+Cの結果
[[ 3  6]
 [ 7 10]
 [11 14]
 [15 18]]

2*Aの結果
[[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 10]]


In [ ]:
#B,Dを引き算
sub = #WRITE ME

#Bに1/2を掛け算
product = #WRITE ME

print(sub)
print(product)

In [ ]:
#全要素に足される
print("スカラーを足し込む")
print(A + 1)
#全行に対して足される，列ベクトルを足しても同じ
print("行ベクトルを足し込む")
print(A + np.array([[1, 2]]))

スカラーを足し込む
[[2 3]
 [3 4]
 [4 5]
 [5 6]]
行ベクトルを足し込む
[[2 4]
 [3 5]
 [4 6]
 [5 7]]


## 行列の内積

### ここは少しややこしいのでよく聞いて復習すること!!

行列の内積は，`順番`と`形`が重要！
行列同士が内積を計算できる時，

`左から掛け算される行列の列数`

と

`右から掛け算される行列の行数`

が同じでないと計算できない．
$$
A = \begin{pmatrix}
        1 & 2 \\
        2 & 3 \\
        3 & 4 \\
        4 & 5
        \end{pmatrix} \\
B = \begin{pmatrix}
        1 & 3 & 5\\
        2 & 4 & 6
        \end{pmatrix}
$$

Aの形は`(4, 2)`

Bの形は`(2, 3)`

今回の例で言うと，`<A, B>`は計算できるが，`<B, A>`は計算できない．

一般に
`(m, n)`の形を持つ行列と`(k, l)`の形を持つ行列の内積を計算するためには`n=k`でなければならない．

計算方法は，
`左から掛け算される行列の行`

と

`右から掛け算される行列の列`

でそれぞれ内積を取る．

例）

$
AB = \begin{pmatrix}
        1 & 2 \\
        2 & 3 \\
        3 & 4 \\
        4 & 5
        \end{pmatrix}
        \begin{pmatrix}
        1 & 3 & 5\\
        2 & 4 & 6
        \end{pmatrix}
        =
        \begin{pmatrix}
        5 & 11 & 17\\
        8 & 18 & 28\\
        11 & 25 & 39 \\
        14 & 32 & 50 
        \end{pmatrix} 
$

今回は，（4, 2）行列と，（2, 3）行列を掛け算して，結果が（4, 3）行列になった．

一般に，(m,n)行列と(n,l)行列を掛け算すると，(m,l)行列になる．

numpyでの計算方法は, `np.dot()`を用いるか，`np.matmul()`または，`@`演算子で計算できる．

In [20]:
# 行列積を計算
print(np.matmul(A, B))

NameError: ignored

In [ ]:
# 行列積CDを計算しよう
CD = #WRITE ME

print(CD)

## 転置行列

$$
A^T
$$
の形で表される．
$$
A = \begin{pmatrix}
        1 & 2 \\
        2 & 3 \\
        3 & 4 \\
        4 & 5
        \end{pmatrix}
$$
である時，

$$
A^T = \begin{pmatrix}
        1 & 2 & 3 & 4\\
        2 & 3 & 4 & 5\\
        \end{pmatrix}
$$
という形で行と列を入れ替えたものである．

つまり(m,n)行列の転置を取ると，(n,m)行列になるということである．

尚，各要素については
$$
A^T_{ij} = A_{ji}
$$

という関係がある．

例）転置を使う場面
$$
A = \begin{pmatrix}
        1 & 2 \\
        2 & 3 \\
        3 & 4 \\
        4 & 5
        \end{pmatrix} \\
C = \begin{pmatrix}
        2 & 4 \\
        5 & 7 \\
        8 & 10 \\
        11 & 13 
    \end{pmatrix}
$$
の積を計算したいが，そのままでは（4, 2）行列と（4, 2）行列なので計算できない．

そこで，次のように転置を取ると計算できるようになる．

$$
A^T = \begin{pmatrix}
        1 & 2 & 3 & 4\\
        2 & 3 & 4 & 5\\
        \end{pmatrix} \\
C = \begin{pmatrix}
        2 & 4 \\
        5 & 7 \\
        8 & 10 \\
        11 & 13 
    \end{pmatrix} \\
A^TC =  \begin{pmatrix}
        80 & 100 \\
        106 & 134 
    \end{pmatrix} \\
AC^T = \begin{pmatrix}
        10 & 19 & 28 & 37 \\
        16 & 31 & 46 & 61 \\
        22 & 43 & 64 & 85 \\
        28 & 55 & 82 & 109
    \end{pmatrix} \\
$$

numpyで行列の転置を取る場合は, `np.ndarray.T`でとることができる．

ベクトルの場合はどんなだったか思い出してみよう．

In [ ]:
#転置を取って行列積を計算
print(A.T @ C)
print(A @ C.T)

[[ 80 100]
 [106 134]]
[[ 10  19  28  37]
 [ 16  31  46  61]
 [ 22  43  64  85]
 [ 28  55  82 109]]


In [ ]:
#BとDの行列積を転置を使って計算してみよう
B_T_D = #WRITE ME
B_D_T = #WRITE ME

print(B_T_D)
print(B_D_T)

In [ ]:
#summary
a = np.array([5, 6])
b = np.array([3, 4])
print("sum")
print(a+b)
print("scholar product")
print(2*a)
print("inner product")
print(a @ b)

print("matrix")
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 3 ,5], [2, 4, 6]])
print(A)
print(A.shape)
print("summation and substitution")
print(A+B)
print(A-B)
print("transpose")
print(A.T)
A_T = A.T
print(B@A_T)
print(A_T@B)

sum
[ 8 10]
scholar product
[10 12]
inner product
39
matrix
[[1 2 3]
 [4 5 6]]
(2, 3)
summation and substitution
[[ 2  5  8]
 [ 6  9 12]]
[[ 0 -1 -2]
 [ 2  1  0]]
transpose
[[1 4]
 [2 5]
 [3 6]]
[[22 49]
 [28 64]]
[[ 9 19 29]
 [12 26 40]
 [15 33 51]]
