In [13]:
#numpy ライブラリをインポートする
import numpy as np
import numpy.linalg as nalg
#numpy のnp.ndarrayクラスのインスタンスを生成する

#ベクトル演算
a = np.array([1, 2])
b = np.array([3, 4])

print(a+b)
print(b-a)
print(3*a)
print(a @ b)

#行列演算
A = np.array([[1, 4],
                    [2, 5],
                    [3, 6]])
B = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
print(A)
print(A.shape)
print(A+B)
print(A.T)
print(A.T@B)

[4 6]
[2 2]
[3 6]
11
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[ 2  6]
 [ 5  9]
 [ 8 12]]
[[1 2 3]
 [4 5 6]]
[[22 28]
 [49 64]]


In [17]:
a = np.array([5, 6])
b = np.array([3, 4])
print("sum")
print(a+b)
print("scholar product")
print(2*a)
print("inner product")
print(a @ b)

print("matrix")
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 3 ,5], [2, 4, 6]])
print(A)
print(A.shape)
print("summation and substitution")
print(A+B)
print(A-B)
print("transpose")
print(A.T)
A_T = A.T
print(B@A_T)
print(A_T@B)

sum
[ 8 10]
scholar product
[10 12]
inner product
39
matrix
[[1 2 3]
 [4 5 6]]
(2, 3)
summation and substitution
[[ 2  5  8]
 [ 6  9 12]]
[[ 0 -1 -2]
 [ 2  1  0]]
transpose
[[1 4]
 [2 5]
 [3 6]]
[[22 49]
 [28 64]]
[[ 9 19 29]
 [12 26 40]
 [15 33 51]]
